#### Question 1

Write Python code to create a NumPy array called "salary_array" to store the salaries of five employees. Print the data.

In [1]:
# Answer for Question 1

import numpy as np
list = [60000, 75000, 80000, 90000, 85000]
salary_array = np.array(list)
print(salary_array)

[60000 75000 80000 90000 85000]


#### Question 2

Write Python code to create a 2D NumPy array called "department_salaries" that stores salaries of 2 departments.

In [2]:
# Answer for Question 2

import numpy as np
engineering_salaries = [80000, 85000, 90000, 95000, 92000]
marketing_salaries = [70000, 72000, 75000, 78000, 76000]
total = [engineering_salaries, marketing_salaries]
department_salaries = np.array(total)
print(department_salaries)

[[80000 85000 90000 95000 92000]
 [70000 72000 75000 78000 76000]]


#### Question 3

Employee Number 3 from "salary_array" received a bonus of $5000. Update the salary of the 3rd employee in the "salary_array" and Print the results.

In [3]:
# Answer for Question 3

import numpy as np
list = [60000, 75000, 80000, 90000, 85000]
salary_array = np.array(list)
salary_array[2] = salary_array[2] + 5000
print("Updated Salary Array:", salary_array)

Updated Salary Array: [60000 75000 85000 90000 85000]


#### Question 4

Create a new NumPy array called "new_hires" to store their salaries and then concatenate it with the "salary_array" to update the company's salary data as "updated_salary_array". Print the msg "Updated Salary Array:" to match the expected output.

In [4]:
# Answer for Question 4

import numpy as np
salary_array = np.array([60000, 75000, 80000, 90000, 85000])
new_hires = np.array([72000, 78000, 76000])
updated_salary_array = np.concatenate((salary_array, new_hires))
print("Updated Salary Array:", updated_salary_array)

Updated Salary Array: [60000 75000 80000 90000 85000 72000 78000 76000]


#### Question 5

To organize the salary data, reshape the "salary_array" into a 2D array with two rows and four columns. Save the results in "reshaped_salary_array".

In [5]:
# Answer for Question 5

import numpy as np
salary_array = np.array([60000, 75000, 80000, 90000, 85000, 72000, 78000, 76000])
reshaped_salary_array = salary_array.reshape(2, 4)
print("Reshaped Salary Array:", reshaped_salary_array)

Reshaped Salary Array: [[60000 75000 80000 90000]
 [85000 72000 78000 76000]]
